######################################
# Base Deployment Template for Boomi #
######################################

parameters:
- name: packageVersion
  type: string
- name: componentIds
  type: string
- name: packageName
  type: string
- name: test_componentIds
  type: string
  default: ''
- name: notes
  type: string
- name: postmanCollection
  type: string
  default: ''
- name: sleepInMinutes
  type: number
  default: 0

variables:
  - group: boomicicd
  - group: boomiruntime
  - name: packageVersion
    ${{ if eq(parameters.packageVersion, '0') }}:
      value: ${{ parameters.packageName }}.$(Build.BuildNumber).BUILD
    ${{ if ne(parameters.packageVersion, '0') }}:
      value: ${{ parameters.packageVersion }}

stages:
###########################
# Development: Deployment #
###########################
  - stage: Dev_Deployment
    displayName: Development
    jobs:
      - deployment: update_extensions
        displayName: Update DEV Extensions
        environment: 1_BOOMI-ANZ_DEV  
        variables:
          - group: extensionsdev
        strategy:                 
          runOnce:
            deploy: 
              steps:
                - template: update_extensions.yaml
                  parameters:
                    #####################
                    # Common parameters #
                    #####################
                    h1 : $(h1)
                    h2 : $(h2)
                    baseURL : $(baseURL)
                    authToken: $(authToken)
                    VERBOSE: $(VERBOSE)
                    SLEEP_TIMER: $(SLEEP_TIMER)
                    WORKSPACE: $(WORKSPACE)
                    SCRIPTS_HOME: $(SCRIPTS_HOME)
                    #####################
                    # End of parameters #
                    #####################

      - job: deploy_packages
        displayName: Deploy DEV Packages
        dependsOn:
        - update_extensions
        steps:
          - template: deploy_packages.yaml
            parameters:
              #####################
              # Common parameters #
              #####################
              h1 : $(h1)
              h2 : $(h2)
              baseURL : $(baseURL)
              authToken: $(authToken)
              VERBOSE: $(VERBOSE)
              SLEEP_TIMER: $(SLEEP_TIMER)
              WORKSPACE: $(WORKSPACE)
              SCRIPTS_HOME: $(SCRIPTS_HOME)
              #######################
              # Specific parameters #
              #######################
              componentIds : ${{ parameters.componentIds }},${{ parameters.test_componentIds }}
              env: 1_BOOMI-ANZ_DEV
              notes: ${{ parameters.notes }}
              packageName : ${{ parameters.packageName }}
              packageVersion: $(packageVersion)
              extractComponentXmlFolder: 'componentsExtracted'
              #####################
              # End of parameters #
              #####################

      - job: display_extension_json
        displayName: Display Extension JSON
        dependsOn:
        - update_extensions
        steps:
          - template: display_extensions.yaml
            parameters:
              #####################
              # Common parameters #
              #####################
              h1 : $(h1)
              h2 : $(h2)
              baseURL : $(baseURL)
              authToken: $(authToken)
              VERBOSE: $(VERBOSE)
              SLEEP_TIMER: $(SLEEP_TIMER)
              WORKSPACE: $(WORKSPACE)
              SCRIPTS_HOME: $(SCRIPTS_HOME)
              #####################
              # End of parameters #
              #####################
              
#############################
# Development: Unit Testing #
#############################
  - stage: Dev_UnitTesting
    displayName: Development Unit Tests
    dependsOn: Dev_Deployment
    jobs:
      - job: execute_processes
        displayName: Execute Unit Tests
        steps:
          - ${{if parameters.test_componentIds}}:
            - template: execute_processes.yaml
              parameters:
                #####################
                # Common parameters #
                #####################
                h1 : $(h1)
                h2 : $(h2)
                baseURL : $(baseURL)
                authToken: $(authToken)
                VERBOSE: $(VERBOSE)
                SLEEP_TIMER: $(SLEEP_TIMER)
                WORKSPACE: $(WORKSPACE)
                SCRIPTS_HOME: $(SCRIPTS_HOME)
                #######################
                # Specific parameters #
                #######################
                atomName: $(development_atom)
                componentIds: ${{ parameters.test_componentIds }}
                #####################
                # End of parameters #
                #####################
      - job: validate_processes
        displayName: Validate Unit Tests
        dependsOn: execute_processes
        steps:
          - ${{if parameters.test_componentIds}}:
            - script: |
                export sleepSeconds=$(( ${{ parameters.sleepInMinutes }} * 60 ))
                echo "Sleeping for ${sleepSeconds} seconds ..."
                sleep ${sleepSeconds}
                echo "Sleeping done"
            - template: validate_processes.yaml
              parameters:
                #####################
                # Common parameters #
                #####################
                h1 : $(h1)
                h2 : $(h2)
                baseURL : $(baseURL)
                authToken: $(authToken)
                VERBOSE: $(VERBOSE)
                SLEEP_TIMER: $(SLEEP_TIMER)
                WORKSPACE: $(WORKSPACE)
                SCRIPTS_HOME: $(SCRIPTS_HOME)
                #######################
                # Specific parameters #
                #######################
                atomName: $(development_atom)
                componentIds: ${{ parameters.test_componentIds }}
                #####################
                # End of parameters #
                #####################                    
#############################
# Development: API Testing #
#############################
  - stage: Dev_APITesting
    displayName: Development API Tests
    dependsOn: Dev_Deployment
    jobs:
      - job: call_secretmanager
        displayName: Call secrets manager
        steps:
          - ${{if parameters.postmanCollection}}:
            - template: call_secretmanager.yaml
              parameters:
                #####################
                # Common parameters #
                #####################
                h1 : $(h1)
                h2 : $(h2)
                baseURL : $(baseURL)
                authToken: $(authToken)
                VERBOSE: $(VERBOSE)
                SLEEP_TIMER: $(SLEEP_TIMER)
                WORKSPACE: $(WORKSPACE)
                SCRIPTS_HOME: $(SCRIPTS_HOME)
                #######################
                # Specific parameters #
                #######################
                env: $(development_envname)
                secretMode: 'postman'
                secretName: $(azureKeyvault)
                awsRegion: $(awsRegion)
                awsAccessKeyId: $(awsAccessKeyId)
                awsSecretKey: $(awsSecretKey)
                BOOMI_LIBRARIES: $(BOOMI_LIBRARIES)
                #####################
                # End of parameters #
                #####################
      - job: call_api
        displayName: Test DEV APIs
        dependsOn: call_secretmanager
        steps:
          - ${{if parameters.postmanCollection}}:
            - template: call_api.yaml
              parameters:
                #####################
                # Common parameters #
                #####################
                h1 : $(h1)
                h2 : $(h2)
                baseURL : $(baseURL)
                authToken: $(authToken)
                VERBOSE: $(VERBOSE)
                SLEEP_TIMER: $(SLEEP_TIMER)
                WORKSPACE: $(WORKSPACE)
                SCRIPTS_HOME: $(SCRIPTS_HOME)
                #######################
                # Specific parameters #
                #######################
                postmanCollection : ${{ parameters.postmanCollection }}
                #####################
                # End of parameters #
                #####################
####################
# Test: Deployment #
####################
  - stage: SIT_Deployment
    displayName: SIT
    dependsOn:
      - Dev_UnitTesting
      - Dev_APITesting
    jobs:
      - deployment: update_extensions_sit
        displayName: Update SIT Extensions
        environment: 3_GX_MCS_SIT  
        variables:
          - group: extensionssit
        strategy:                 
          runOnce:
            deploy: 
              steps:
                - template: update_extensions.yaml
                  parameters:
                    #####################
                    # Common parameters #
                    #####################
                    h1 : $(h1)
                    h2 : $(h2)
                    baseURL : $(baseURL)
                    authToken: $(authToken)
                    VERBOSE: $(VERBOSE)
                    SLEEP_TIMER: $(SLEEP_TIMER)
                    WORKSPACE: $(WORKSPACE)
                    SCRIPTS_HOME: $(SCRIPTS_HOME)
                    #####################
                    # End of parameters #
                    #####################              
      - job: deploy_packages
        displayName: Deploy SIT Packages
        dependsOn:
        - update_extensions_sit
        steps:
          - template: deploy_packages.yaml
            parameters:
              #####################
              # Common parameters #
              #####################
              h1 : $(h1)
              h2 : $(h2)
              baseURL : $(baseURL)
              authToken: $(authToken)
              VERBOSE: $(VERBOSE)
              SLEEP_TIMER: $(SLEEP_TIMER)
              WORKSPACE: $(WORKSPACE)
              SCRIPTS_HOME: $(SCRIPTS_HOME)
              #######################
              # Specific parameters #
              #######################
              componentIds : ${{ parameters.componentIds }}
              env: 3_GX_MCS_SIT
              notes: ${{ parameters.notes }}
              packageName : ${{ parameters.packageName }}
              packageVersion: $(packageVersion)
              extractComponentXmlFolder: 'componentsExtracted'
              #####################
              # End of parameters #
              #####################
        
####################
# UAT: Deployment #
####################
  - stage: UAT_Deployment
    displayName: UAT
    dependsOn:
      - SIT_Deployment
    jobs:
      - deployment: update_extensions_uat
        displayName: Update UAT Extensions
        environment: 4_GX_MCS_UAT
        variables:
          - group: extensionsuat
        strategy:                 
          runOnce:
            deploy: 
              steps:
                - template: update_extensions.yaml
                  parameters:
                    #####################
                    # Common parameters #
                    #####################
                    h1 : $(h1)
                    h2 : $(h2)
                    baseURL : $(baseURL)
                    authToken: $(authToken)
                    VERBOSE: $(VERBOSE)
                    SLEEP_TIMER: $(SLEEP_TIMER)
                    WORKSPACE: $(WORKSPACE)
                    SCRIPTS_HOME: $(SCRIPTS_HOME)
                    #####################
                    # End of parameters #
                    #####################              
      - job: deploy_packages
        displayName: Deploy UAT Packages
        dependsOn:
        - update_extensions_uat
        steps:
          - template: deploy_packages.yaml
            parameters:
              #####################
              # Common parameters #
              #####################
              h1 : $(h1)
              h2 : $(h2)
              baseURL : $(baseURL)
              authToken: $(authToken)
              VERBOSE: $(VERBOSE)
              SLEEP_TIMER: $(SLEEP_TIMER)
              WORKSPACE: $(WORKSPACE)
              SCRIPTS_HOME: $(SCRIPTS_HOME)
              #######################
              # Specific parameters #
              #######################
              componentIds : ${{ parameters.componentIds }}
              env: 4_GX_MCS_UAT
              notes: ${{ parameters.notes }}
              packageName : ${{ parameters.packageName }}
              packageVersion: $(packageVersion)
              extractComponentXmlFolder: 'componentsExtracted'
              #####################
              # End of parameters #
              #####################
                    
        
####################
# Prod: Deployment #
####################
  - stage: Prod_Deployment
    displayName: Production
    dependsOn:
      - UAT_Deployment
    jobs:
      - deployment: update_extensions_prod
        displayName: Update Prod Extensions
        environment: 5_GX_MCS_PROD
        variables:
          - group: extensionsprod
        strategy:                 
          runOnce:
            deploy: 
              steps:
                - template: update_extensions.yaml
                  parameters:
                    #####################
                    # Common parameters #
                    #####################
                    h1 : $(h1)
                    h2 : $(h2)
                    baseURL : $(baseURL)
                    authToken: $(authToken)
                    VERBOSE: $(VERBOSE)
                    SLEEP_TIMER: $(SLEEP_TIMER)
                    WORKSPACE: $(WORKSPACE)
                    SCRIPTS_HOME: $(SCRIPTS_HOME)
                    #####################
                    # End of parameters #
                    #####################              
      - job: deploy_packages
        displayName: Deploy Prod Packages
        dependsOn:
        - update_extensions_prod
        steps:
          - template: deploy_packages.yaml
            parameters:
              #####################
              # Common parameters #
              #####################
              h1 : $(h1)
              h2 : $(h2)
              baseURL : $(baseURL)
              authToken: $(authToken)
              VERBOSE: $(VERBOSE)
              SLEEP_TIMER: $(SLEEP_TIMER)
              WORKSPACE: $(WORKSPACE)
              SCRIPTS_HOME: $(SCRIPTS_HOME)
              #######################
              # Specific parameters #
              #######################
              componentIds : ${{ parameters.componentIds }}
              env: 5_GX_MCS_PROD
              notes: ${{ parameters.notes }}
              packageName : ${{ parameters.packageName }}
              packageVersion: $(packageVersion)
              extractComponentXmlFolder: 'componentsExtracted'
              #####################
              # End of parameters #
              #####################
                    
              